import { Router } from "express";
import mongoose from "mongoose";
import { Channel } from "../models/Channel.js";
import { JenkinsIntegration } from "../models/JenkinsIntegration.js";
import { requireAuth } from "../middleware/requireAuth.js";
import { requireAdmin } from "../middleware/requireAdmin.js";
import { createJenkinsToken, decryptJenkinsToken, encryptJenkinsToken, findJenkinsIntegration, hashJenkinsToken, integrationEndpointPath, JENKINS_NOTIFY_KEYS, processJenkinsEvent } from "../jenkins.js";

export const jenkinsWebhookRouter = Router();
jenkinsWebhookRouter.post("/:token", async (req, res) => { const integration = await findJenkinsIntegration(req.params.token); if (!integration) return res.status(404).json({ error: "integration not found" }); try { const result = await processJenkinsEvent(integration, req.body || {}); res.status(result.duplicate ? 200 : 202).json(result); } catch (error) { await JenkinsIntegration.updateOne({ _id: integration._id }, { $set: { lastError: String(error?.message || "event processing failed").slice(0, 500) } }); throw error; } });

export const jenkinsRouter = Router();
jenkinsRouter.use(jenkinsWebhookRouter);
jenkinsRouter.use(requireAuth, requireAdmin);
async function resolveChannel(channelId) { return mongoose.isValidObjectId(channelId) ? Channel.findOne({ _id: channelId, type: "public", isArchived: false }) : null; }
async function publicIntegration(item) { const channel = item.channel ? await Channel.findById(item.channel) : null; const token = decryptJenkinsToken(item.tokenCiphertext); return { ...item.toPublicJSON(), channelName: channel?.name || null, endpoint: token ? integrationEndpointPath(token) : null }; }
jenkinsRouter.get("/", async (_req, res) => { const integrations = await JenkinsIntegration.find().sort({ createdAt: -1 }).limit(1); res.json({ integrations: await Promise.all(integrations.map(publicIntegration)) }); });
jenkinsRouter.post("/", async (req, res) => { if (await JenkinsIntegration.findOne()) return res.status(409).json({ error: "Jenkins is already configured" }); const name = String(req.body?.name || "Jenkins").trim(); if (!name || name.length > 80) return res.status(400).json({ error: "name is required and must be at most 80 characters" }); const channel = await resolveChannel(req.body?.channelId) || await Channel.findOne({ name: "general", type: "public", isArchived: false }); if (!channel) return res.status(400).json({ error: "a public destination channel is required" }); const token = createJenkinsToken(); const integration = await JenkinsIntegration.create({ name, channel: channel._id, tokenHash: hashJenkinsToken(token), tokenCiphertext: encryptJenkinsToken(token), createdBy: req.user._id, notify: req.body?.notify || {} }); res.status(201).json({ integration: await publicIntegration(integration), token, endpointPath: integrationEndpointPath(token) }); });
jenkinsRouter.post("/:id/token", async (req, res) => { const integration = await JenkinsIntegration.findById(req.params.id); if (!integration) return res.status(404).json({ error: "integration not found" }); const token = createJenkinsToken(); integration.tokenHash = hashJenkinsToken(token); integration.tokenCiphertext = encryptJenkinsToken(token); await integration.save(); res.json({ endpoint: integrationEndpointPath(token), token }); });
jenkinsRouter.patch("/:id", async (req, res) => { const integration = await JenkinsIntegration.findById(req.params.id); if (!integration) return res.status(404).json({ error: "integration not found" }); if (req.body?.name !== undefined) { const name = String(req.body.name).trim(); if (!name || name.length > 80) return res.status(400).json({ error: "invalid integration name" }); integration.name = name; } if (req.body?.channelId !== undefined) { const channel = await resolveChannel(req.body.channelId); if (!channel) return res.status(400).json({ error: "a public destination channel is required" }); integration.channel = channel._id; } if (req.body?.active !== undefined) integration.active = !!req.body.active; if (req.body?.notify && typeof req.body.notify === "object") for (const key of JENKINS_NOTIFY_KEYS) if (req.body.notify[key] !== undefined) integration.notify[key] = !!req.body.notify[key]; await integration.save(); res.json({ integration: await publicIntegration(integration) }); });
