{{- if and .Values.enabled .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "minio.serviceName" . }}-data
  labels:
    {{- include "minio.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
  {{- with .Values.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- with .Values.global.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
{{- end }}
